
name: Windows GiReactorTest

on:
  push:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      ref:
        description: "Enter a tag or commit to package"
        default: ""

jobs:
  windows_test:
    runs-on: windows-2022
    strategy:
      matrix:
        arch: [x64, x86]
        python: ["3.12"]
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
          ref: 11987-gi-reactor-tests-win

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python}}
          architecture: ${{ matrix.arch }}
          cache: pip
      - name: Install base build deps
        run: |
          pip install wheel setuptools

      # Make sure the matrix is defined in such a way that this is triggered
      # only on Linux.
      - name: Install GTK system deps on windows
        run: |
          $WebClient = New-Object System.Net.WebClient
          $WebClient.DownloadFile("https://github.com/doadin/gvsbuild-release/releases/download/latest/gvsbuild-py${{ matrix.python }}-vs17-${{ matrix.arch }}.zip","C:\GTK.zip")
          7z x C:\GTK.zip -oc:\GTK
          echo "C:\GTK\release\lib" | Out-File -FilePath $env:GITHUB_PATH -Append
          echo "C:\GTK\release\bin" | Out-File -FilePath $env:GITHUB_PATH -Append
          echo "C:\GTK\release" | Out-File -FilePath $env:GITHUB_PATH -Append
          python -m pip install --no-index --find-links="C:\GTK\release\python" pycairo PyGObject

      - name: Install Twisted from source
        run: |
          pip install -e .

      - name: Test GI reactor import
        shell: pwsh
        run: |
          $code = @"
          from twisted.internet import defer, gtk3reactor
          print("Import OK")
          reactor = gtk3reactor.install()
          print("Reactor installed:", reactor)
          "@
          python -c "$code"

      - name: Build Twisted wheel
        run: |
          pip install build
          python -m build --wheel --outdir dist


      - name: Upload wheel artifact
        uses: actions/upload-artifact@v4
        with:
          name: twisted-wheel-py${{ matrix.python }}-${{ matrix.arch }}
          path: dist/*.whl
